'use client'

import { useLang } from '@/lib/plugin-sdk'

/**
 * Live TV-vyernas texter bor i pluginet: pluginet auto-uppdateras oberoende
 * av appen, så nya nycklar i appens i18n hade gett råa nyckelnamn i äldre
 * appar. `{namn}` ersätts med vars.
 */
const EN = {
  categories: 'Categories',
  curationSummary: '{groups} categories · {hidden} hidden · {merged} merged',
  showAll: 'Show all',
  hideAll: 'Hide all',
  mergeInto: 'Merge into…',
  mergeHint: 'To merge categories: press Mark on two or more rows, then give the merged category a name.',
  mergeAction: 'Merge',
  mergeSelected: 'Merge selected ({n})',
  splitMerge: 'Split',
  mergeContains: 'Contains {groups}',
  markForMerge: 'Mark',
  save: 'Save',
  skip: 'Skip',
  mergeNameLabel: 'Name of the merged category',
  mergeNameEmpty: 'Give the category a name.',
  mergeNameTaken: 'A merged category with that name already exists.',
  mergeNameIsGroup: 'That name is already a visible category.',
  noCategoriesInList: 'This playlist has no categories.',
  searchCategories: 'Search categories',
  curationIntro: 'Choose which categories to show. You can change this later under the playlist\u2019s settings.',
  allCategoriesHidden: 'All categories in this playlist are hidden.',
  openCategories: 'Choose categories',
  // Gemensamt
  back: 'Back',
  search: 'Search',
  reminders: 'Reminders',
  hubLive: 'LIVE',
  hubWatchNow: 'Watch now',
  hubNoProgramme: 'No programme information',
  hubLoadingEpg: 'Fetching guide…',
  channelsCount: '{count} channels',
  minutesLeft: '{min} min left',
  // Hubb
  hubGuideKicker: 'Full channel guide',
  // EPG
  // Kanaldetalj
  today: 'Today',
  channelInfo: 'Channel information',
  quality: 'Quality',
  yes: 'Yes',
  no: 'No',
  unknown: 'Unknown',
  parental: 'Parental control',
  enterPin: 'Enter the profile PIN',
  pinWrong: 'Wrong PIN. Try again.',
  unlock: 'Unlock',
  cancel: 'Cancel',
  // Spelare
  guide: 'Guide',
  // Sök
  searchPlaceholder: 'Search channels and programmes',
  noResults: 'Nothing matched "{query}".',
  // Påminnelser
  remindersEmpty: 'No reminders. Tap the bell on a programme to add one.',
  remove: 'Remove',
  startsNow: 'Starts now on {channel}',
  startsIn: 'Starts in {min} min on {channel}',
  watch: 'Watch',
  dismiss: 'Dismiss',
  // M3U-hämtning
  m3uFetchProgress: 'Fetching list {current} of {total}…',
  m3uFetchedAt: 'fetched {time}',
  m3uNeverFetched: 'not fetched yet',
  m3uFetchFailedOn: 'Could not fetch {host}: {error}',
  m3uFetchKeepOpen: 'This can take a while for a large playlist. You can leave this page — the fetch keeps running.',
  // EPG-diagnostik (appens butik, /api/live-tv/epg/status)
  epgStatusTitle: 'Programme guide status',
  epgStatusAllLists: 'The guide is fetched once for every playlist together.',
  epgSourceStats: '{channels} channels · {programmes} programmes',
  epgSourceFetched: 'fetched {time}',
  epgFetchedAt: 'Guide fetched {time} · {programmes} programmes',
  epgNeverFetched: 'The guide has not been fetched yet.',
  epgRefresh: 'Refetch EPG',
  epgRefreshing: 'Fetching…',
  // Import-UX
  listNeedsReimport: 'Needs refetching',
  listRefetch: 'Refetch',
  listRefetching: 'Fetching…',
  listImportProgress: 'Fetching {received} of {total}…',
  listImportProgressUnknown: 'Fetching…',
  listImportParsing: 'Reading the playlist…',
  listImportWriting: 'Saving the channels…',
  listImportFailed: 'The fetch failed: {error}',
  listTruncated: 'The playlist was cut off at 64 MiB — some channels are missing',
  appTooOld: 'Live TV requires Lumio 0.1.596 or newer',
  listFull: 'The list is full — 500 channels at most',
  xtreamNeedsLogin: 'Sign in again to fetch channels',
  xtreamRelogin: 'Sign in again',
  // Logotypreserv (P5)
  logoFallbackToggle: 'Fill in missing logos from iptv-org',
  logoFallbackHint: 'Lets the list use the iptv-org logo registry when a channel has none of its own.',
  logoComplete: 'Complete',
  logoCompleteRunning: 'Completing…',
  logoCompleteResult: '{matched} of {total} completed',
  // Flerlistekörningen (Jerrys granskningsfynd): scope + framsteg syns i
  // knappens egen text, en enda lista ser fortfarande ut som `logoCompleteRunning`.
  logoCompleteRunningProgress: 'Completing list {current} of {total}…',
  // Delresultatet innan ett fel mitt i en flerlistekörning — `{error}` är
  // appens egen feltext, ordagrant, inte en omskriven variant.
  logoCompletePartialError: '{completed} of {total} lists completed — then: {error}',
  // Komplettera-knappen i själva Live TV-vyn — en egen handling, skild från
  // ovanstående switch (som bara styr OM reserven får användas).
  logoCompleteButton: 'Complete logos',
  // P8
  xtreamAccountUnavailable: 'Could not read the account',
  xtreamExpires: 'expires {date}',
  xtreamNoExpiry: 'no expiry date',
  xtreamMaxConnections: '{count} connections',
  // Inställningssidan enligt handoff 2026-09-24 (copy ordagrant, §3–§4)
  useAsHome: 'Use as home page',
  useAsHomeDesc: 'Replaces the regular Home rows with the Live TV view but keeps the hero and the rest of the start page.',
  hideHero: 'Hide the movie hero on the Live TV page',
  hideHeroDesc: 'Live TV then starts with the hub instead of below the app\u2019s hero carousel.',
  playlists: 'Playlists',
  yourPlaylists: 'Your playlists',
  playlistsHint: 'Each playlist keeps its own categories and EPG sources.',
  noPlaylistsYet: 'No playlists yet. Add an M3U link or an Xtream login below.',
  m3uTitle: 'M3U Playlist URLs',
  m3uHint: 'Enter one M3U URL per line. Channels are stored in your browser.',
  playlistUrl: 'Playlist URL',
  fetchList: 'Fetch list',
  xtreamLogin: 'Xtream login',
  xtreamHint: 'For providers that use an Xtream Codes login (server, username, password) instead of an M3U link.',
  serverUrl: 'Server URL',
  username: 'Username',
  password: 'Password',
  loginAndFetch: 'Log in & fetch',
  loggingIn: 'Logging in\u2026',
  loginFetched: 'Fetched',
  loginRejected: 'Login rejected \u2014 check the username and password.',
  loginUnreachable: 'Could not reach the panel. Check the server URL.',
  useAsLibrary: 'Use as library',
  useAsLibraryHint: 'Build a library index from the film and series in this playlist. The library can then own the home page, the same way Plex and Jellyfin can.',
  kindM3u: 'M3U',
  kindXtream: 'Xtream',
  kindCustom: 'Custom list',
  fetching: 'Fetching\u2026',
  updateChannels: 'Update channels',
  playlistMeta: '{kind} · {channels} channels · {fetched}',
  epgSources: 'EPG sources',
  noEpgSourceYet: 'No EPG source for this playlist yet.',
  xmltvPlaceholder: 'XMLTV URL (e.g. https://epgshare01.online/epgshare01/epg_ripper_SE1.xml.gz)',
  add: 'Add',
  on: 'On',
  pasteXmltvFirst: 'Paste an XMLTV URL first',
  epgSourceAdded: 'EPG source added',
  epgSourceRemoved: 'EPG source removed',
  removePlaylistTitle: 'Remove {host}?',
  removePlaylistBody: 'Channels, categories and EPG sources from this playlist are removed from Live TV.',
  hostRemoved: '{host} removed',
  hostUpdated: '{host} updated',
  guideFetchedToast: 'Guide fetched · {programmes} programmes',
  fetchingGuide: 'Fetching the guide\u2026',
  libraryBuiltToast: 'Library built · {count} titles',
  libraryBuilt: 'Library built · {count} titles indexed',
  titlesReady: '{count} titles ready to index',
  categoriesTitle: 'Categories · {host}',
  categoriesBody: 'Hide the ones you never watch and merge the ones that belong together.',
  merged: 'Merged',
  mergedMeta: '{members} · {channels} channels',
  mark: 'Mark',
  marked: 'Marked',
  mergeN: 'Merge {n}',
  mergeNameSuggest: 'Name the merged category',
  giveMergedName: 'Give the merged category a name',
  mergeHelp: 'To merge categories: press Mark on two or more rows, then give the merged category a name.',
  categoriesSaved: 'Categories saved',
  mergedInto: 'Merged into {name}',
  splitDone: '{name} split',
  renamedTo: 'Renamed to {name}',
  // TV-vyerna (handoff §4.2)
  tvNotSet: 'Not set',
  tvM3uUrls: 'M3U URLs',
  tvM3uHint: 'One per line \u2014 https://example.com/playlist.m3u. Entered on the phone for long addresses.',
  tvFetch: 'Fetch',
  tvLogin: 'Log in',
  tvLoginHint: 'Signs in and fetches the channel list',
  tvStatus: 'Status',
  tvChannels: 'Channels',
  tvEdit: 'Edit',
  tvUpdate: 'Update',
  tvUpdateHint: 'Fetches the channel list again',
  tvAutoEpgMeta: 'Auto · url-tvg from the playlist',
  tvManualEpgMeta: 'Added by hand',
  tvAddXmltv: 'Add XMLTV URL',
  tvAddXmltvMeta: 'e.g. https://epgshare01.online/epgshare01/epg_ripper_SE1.xml.gz',
  tvPlaylistEyebrow: 'Playlist',
  tvRemovePlaylist: 'Remove playlist',
  tvRemovePlaylistMeta: 'Channels and categories from this list disappear from Live TV',
  tvComplete: 'Complete',
  tvMergeCategories: 'Merge categories',
  tvMergeNCategories: 'Merge {n} categories',
  tvMarkTwoOrMore: 'Mark two or more',
  tvMarkAtLeastTwo: 'Mark at least two categories',
  tvRename: 'Rename',
  tvSplitName: 'Split {name}',
  tvSplitMeta: 'The categories return as separate rows',
  tvMarkEyebrow: 'Mark the categories to merge',
  tvMergeHelp: 'To merge categories: press Merge categories, mark two or more rows, then give the merged category a name. It shows as one row in Live TV.',
  tvNameMerged: 'Name the merged category',
  tvRenameMerged: 'Rename merged category',
  tvUseName: 'Use \u201c{name}\u201d',
  tvClear: 'Clear',
  tvSaveName: 'Save name',
  giveCategoryName: 'Give the category a name',
  tvGuideFetched: 'Guide fetched {time}',
  nCategories: '{n} categories',
  nHidden: '{n} hidden',
  nMerged: '{n} merged',
  // Xtreams kategorival på servern + Komplettera logotyper (Jerry 2026-09-24: ingen funktionalitet bort)
  serverCategories: 'Server categories',
  serverCategoriesAll: 'Server categories · all',
  serverCategoriesCount: 'Server categories · {n} of {total}',
  serverCategoriesSelected: 'Server categories · {n} selected',
  serverCategoriesTitle: 'Server categories · {host}',
  serverCategoriesBody: 'Choose which of the panel\u2019s categories are fetched. Unticked categories never enter Live TV.',
  allCategories: 'All categories',
  applyAndFetch: 'Apply & fetch',
  tvAllFetched: 'All categories are fetched',
  tvNOfFetched: '{n} of {total} fetched',
  tvNSelected: '{n} selected',
  completeLogosHint: 'Fetches missing logos from iptv-org now',
  tvNoKeyboard: 'Text entry needs a newer Lumio',
} as const

const SV: Record<keyof typeof EN, string> = {
  categories: 'Kategorier',
  curationSummary: '{groups} kategorier · {hidden} dolda · {merged} ihopslagna',
  showAll: 'Visa alla',
  hideAll: 'Dölj alla',
  mergeInto: 'Slå ihop till…',
  mergeHint: 'Slå ihop kategorier: tryck Markera på två eller fler rader och ge den ihopslagna kategorin ett namn.',
  mergeAction: 'Slå ihop',
  mergeSelected: 'Slå ihop markerade ({n})',
  splitMerge: 'Dela upp',
  mergeContains: 'Innehåller {groups}',
  markForMerge: 'Markera',
  save: 'Spara',
  skip: 'Hoppa över',
  mergeNameLabel: 'Namn på den ihopslagna kategorin',
  mergeNameEmpty: 'Ge kategorin ett namn.',
  mergeNameTaken: 'Det finns redan en ihopslagen kategori med det namnet.',
  mergeNameIsGroup: 'Det namnet är redan en synlig kategori.',
  noCategoriesInList: 'Den här spellistan har inga kategorier.',
  searchCategories: 'Sök kategorier',
  curationIntro: 'Välj vilka kategorier som ska visas. Du kan ändra det senare under spellistans inställningar.',
  allCategoriesHidden: 'Alla kategorier i den här spellistan är dolda.',
  openCategories: 'Välj kategorier',
  back: 'Tillbaka',
  search: 'Sök',
  reminders: 'Påminnelser',
  hubLive: 'LIVE',
  hubWatchNow: 'Titta nu',
  hubNoProgramme: 'Ingen programinformation',
  hubLoadingEpg: 'Hämtar tablå…',
  channelsCount: '{count} kanaler',
  minutesLeft: '{min} min kvar',
  hubGuideKicker: 'Full kanalguide',
  today: 'Idag',
  channelInfo: 'Kanalinformation',
  quality: 'Kvalitet',
  yes: 'Ja',
  no: 'Nej',
  unknown: 'Okänt',
  parental: 'Föräldrakontroll',
  enterPin: 'Ange profilens PIN-kod',
  pinWrong: 'Fel PIN-kod. Försök igen.',
  unlock: 'Lås upp',
  cancel: 'Avbryt',
  guide: 'Guide',
  searchPlaceholder: 'Sök kanaler och program',
  noResults: 'Inget matchade "{query}".',
  remindersEmpty: 'Inga påminnelser. Tryck på klockan på ett program för att lägga till en.',
  remove: 'Ta bort',
  startsNow: 'Börjar nu på {channel}',
  startsIn: 'Börjar om {min} min på {channel}',
  watch: 'Titta',
  dismiss: 'Stäng',
  // M3U-hämtning
  m3uFetchProgress: 'Hämtar lista {current} av {total}…',
  m3uFetchedAt: 'hämtad {time}',
  m3uNeverFetched: 'inte hämtad än',
  m3uFetchFailedOn: 'Kunde inte hämta {host}: {error}',
  m3uFetchKeepOpen: 'En stor spellista kan ta en stund. Du kan lämna sidan — hämtningen fortsätter.',
  epgStatusTitle: 'Tablåns status',
  epgStatusAllLists: 'Tablån hämtas en gång för alla spellistor tillsammans.',
  epgSourceStats: '{channels} kanaler · {programmes} program',
  epgSourceFetched: 'hämtad {time}',
  epgFetchedAt: 'Tablån hämtad {time} · {programmes} program',
  epgNeverFetched: 'Tablån är inte hämtad än.',
  epgRefresh: 'Hämta om EPG',
  epgRefreshing: 'Hämtar…',
  listNeedsReimport: 'Behöver hämtas om',
  listRefetch: 'Hämta om',
  listRefetching: 'Hämtar…',
  listImportProgress: 'Hämtar {received} av {total}…',
  listImportProgressUnknown: 'Hämtar…',
  listImportParsing: 'Läser spellistan…',
  listImportWriting: 'Sparar kanalerna…',
  listImportFailed: 'Hämtningen misslyckades: {error}',
  listTruncated: 'Spellistan kapades vid 64 MiB – vissa kanaler saknas',
  appTooOld: 'Live TV kräver Lumio 0.1.596 eller nyare',
  listFull: 'Listan är full — högst 500 kanaler',
  xtreamNeedsLogin: 'Logga in på nytt för att hämta kanaler',
  xtreamRelogin: 'Logga in på nytt',
  logoFallbackToggle: 'Fyll i saknade logotyper från iptv-org',
  logoFallbackHint: 'Låter listan använda iptv-orgs logotypregister när en kanal saknar egen logotyp.',
  logoComplete: 'Komplettera',
  logoCompleteRunning: 'Kompletterar…',
  logoCompleteResult: '{matched} av {total} kompletterade',
  logoCompleteRunningProgress: 'Kompletterar lista {current} av {total}…',
  logoCompletePartialError: '{completed} av {total} listor klara — sedan: {error}',
  logoCompleteButton: 'Komplettera logotyper',
  // P8
  xtreamAccountUnavailable: 'Kunde inte läsa kontot',
  xtreamExpires: 'giltigt till {date}',
  xtreamNoExpiry: 'inget utgångsdatum',
  xtreamMaxConnections: '{count} anslutningar',
  useAsHome: 'Använd som startsida',
  useAsHomeDesc: 'Ersätter de vanliga Hem-raderna med Live TV-vyn men behåller hjälten och resten av startsidan.',
  hideHero: 'Dölj filmhjälten på Live TV-sidan',
  hideHeroDesc: 'Live TV börjar då med hubben i stället för under appens hjältekarusell.',
  playlists: 'Spellistor',
  yourPlaylists: 'Dina spellistor',
  playlistsHint: 'Varje spellista har sina egna kategorier och EPG-källor.',
  noPlaylistsYet: 'Inga spellistor än. Lägg till en M3U-länk eller en Xtream-inloggning nedan.',
  m3uTitle: 'M3U-spellistans adresser',
  m3uHint: 'Ange en M3U-adress per rad. Kanalerna sparas i din webbläsare.',
  playlistUrl: 'Spellistans adress',
  fetchList: 'Hämta lista',
  xtreamLogin: 'Xtream-inloggning',
  xtreamHint: 'För leverantörer med Xtream Codes-inloggning (server, användarnamn, lösenord) i stället för M3U-länk.',
  serverUrl: 'Server-URL',
  username: 'Användarnamn',
  password: 'Lösenord',
  loginAndFetch: 'Logga in & hämta',
  loggingIn: 'Loggar in\u2026',
  loginFetched: 'Hämtat',
  loginRejected: 'Inloggningen nekades \u2014 kontrollera användarnamn och lösenord.',
  loginUnreachable: 'Kunde inte nå panelen. Kontrollera server-URL:en.',
  useAsLibrary: 'Använd som bibliotek',
  useAsLibraryHint: 'Bygg ett biblioteksindex av filmerna och serierna i spellistan. Biblioteket kan sedan äga startsidan, på samma sätt som Plex och Jellyfin kan.',
  kindM3u: 'M3U',
  kindXtream: 'Xtream',
  kindCustom: 'Egen lista',
  fetching: 'Hämtar\u2026',
  updateChannels: 'Uppdatera kanaler',
  playlistMeta: '{kind} · {channels} kanaler · {fetched}',
  epgSources: 'EPG-källor',
  noEpgSourceYet: 'Ingen EPG-källa för den här spellistan än.',
  xmltvPlaceholder: 'XMLTV-URL (t.ex. https://epgshare01.online/epgshare01/epg_ripper_SE1.xml.gz)',
  add: 'Lägg till',
  on: 'På',
  pasteXmltvFirst: 'Klistra in en XMLTV-adress först',
  epgSourceAdded: 'EPG-källa tillagd',
  epgSourceRemoved: 'EPG-källa borttagen',
  removePlaylistTitle: 'Ta bort {host}?',
  removePlaylistBody: 'Kanaler, kategorier och EPG-källor från den här spellistan tas bort ur Live TV.',
  hostRemoved: '{host} borttagen',
  hostUpdated: '{host} uppdaterad',
  guideFetchedToast: 'Tablån hämtad · {programmes} program',
  fetchingGuide: 'Hämtar tablån\u2026',
  libraryBuiltToast: 'Biblioteket byggt · {count} titlar',
  libraryBuilt: 'Biblioteket byggt · {count} titlar indexerade',
  titlesReady: '{count} titlar redo att indexeras',
  categoriesTitle: 'Kategorier · {host}',
  categoriesBody: 'Dölj de du aldrig tittar på och slå ihop de som hör ihop.',
  merged: 'Ihopslagna',
  mergedMeta: '{members} · {channels} kanaler',
  mark: 'Markera',
  marked: 'Markerad',
  mergeN: 'Slå ihop {n}',
  mergeNameSuggest: 'Namnge den ihopslagna kategorin',
  giveMergedName: 'Ge den ihopslagna kategorin ett namn',
  mergeHelp: 'Slå ihop kategorier: tryck Markera på två eller fler rader och ge den ihopslagna kategorin ett namn.',
  categoriesSaved: 'Kategorierna sparade',
  mergedInto: 'Ihopslagen till {name}',
  splitDone: '{name} uppdelad',
  renamedTo: 'Bytte namn till {name}',
  tvNotSet: 'Inte angiven',
  tvM3uUrls: 'M3U-adresser',
  tvM3uHint: 'En per rad \u2014 https://example.com/playlist.m3u. Skrivs in på telefonen för långa adresser.',
  tvFetch: 'Hämta',
  tvLogin: 'Logga in',
  tvLoginHint: 'Loggar in och hämtar kanallistan',
  tvStatus: 'Status',
  tvChannels: 'Kanaler',
  tvEdit: 'Ändra',
  tvUpdate: 'Uppdatera',
  tvUpdateHint: 'Hämtar kanallistan igen',
  tvAutoEpgMeta: 'Auto · url-tvg ur spellistan',
  tvManualEpgMeta: 'Tillagd för hand',
  tvAddXmltv: 'Lägg till XMLTV-adress',
  tvAddXmltvMeta: 't.ex. https://epgshare01.online/epgshare01/epg_ripper_SE1.xml.gz',
  tvPlaylistEyebrow: 'Spellista',
  tvRemovePlaylist: 'Ta bort spellistan',
  tvRemovePlaylistMeta: 'Kanaler och kategorier från listan försvinner ur Live TV',
  tvComplete: 'Klart',
  tvMergeCategories: 'Slå ihop kategorier',
  tvMergeNCategories: 'Slå ihop {n} kategorier',
  tvMarkTwoOrMore: 'Markera två eller fler',
  tvMarkAtLeastTwo: 'Markera minst två kategorier',
  tvRename: 'Byt namn',
  tvSplitName: 'Dela upp {name}',
  tvSplitMeta: 'Kategorierna kommer tillbaka som egna rader',
  tvMarkEyebrow: 'Markera kategorierna som ska slås ihop',
  tvMergeHelp: 'Slå ihop kategorier: tryck Slå ihop kategorier, markera två eller fler rader och ge den ihopslagna kategorin ett namn. Den visas som en rad i Live TV.',
  tvNameMerged: 'Namnge den ihopslagna kategorin',
  tvRenameMerged: 'Byt namn på ihopslagen kategori',
  tvUseName: 'Använd \u201d{name}\u201d',
  tvClear: 'Rensa',
  tvSaveName: 'Spara namn',
  giveCategoryName: 'Ge kategorin ett namn',
  tvGuideFetched: 'Tablån hämtad {time}',
  nCategories: '{n} kategorier',
  nHidden: '{n} dolda',
  nMerged: '{n} ihopslagna',
  serverCategories: 'Kategorier på servern',
  serverCategoriesAll: 'Kategorier på servern · alla',
  serverCategoriesCount: 'Kategorier på servern · {n} av {total}',
  serverCategoriesSelected: 'Kategorier på servern · {n} valda',
  serverCategoriesTitle: 'Kategorier på servern · {host}',
  serverCategoriesBody: 'Välj vilka av panelens kategorier som hämtas. Avbockade kategorier kommer aldrig in i Live TV.',
  allCategories: 'Alla kategorier',
  applyAndFetch: 'Tillämpa & hämta',
  tvAllFetched: 'Alla kategorier hämtas',
  tvNOfFetched: '{n} av {total} hämtas',
  tvNSelected: '{n} valda',
  completeLogosHint: 'Hämtar saknade logotyper från iptv-org nu',
  tvNoKeyboard: 'Textinmatning kräver en nyare Lumio',
}

export type HubStringKey = keyof typeof EN

export function hubText(lang: string | undefined, key: HubStringKey, vars?: Record<string, string | number>): string {
  const table = lang === 'sv' ? SV : EN
  let out: string = table[key] ?? EN[key]
  if (vars) {
    for (const [name, value] of Object.entries(vars)) out = out.split(`{${name}}`).join(String(value))
  }
  return out
}

export function useHubText() {
  const lang: string = useLang().lang
  const locale = lang === 'sv' ? 'sv-SE' : 'en-GB'
  return {
    lang,
    locale,
    h: (key: HubStringKey, vars?: Record<string, string | number>) => hubText(lang, key, vars),
  }
}
