'use client'

import { useLang } from '@/lib/plugin-sdk'

/**
 * Live TV-vyernas texter bor i pluginet: pluginet auto-uppdateras oberoende
 * av appen, så nya nycklar i appens i18n hade gett råa nyckelnamn i äldre
 * appar. `{namn}` ersätts med vars.
 */
const EN = {
  // Gemensamt
  hubTitle: 'Live TV',
  back: 'Back',
  search: 'Search',
  reminders: 'Reminders',
  hubAllGroups: 'All',
  hubLive: 'LIVE',
  hubWatchNow: 'Watch now',
  pip: 'Picture-in-picture',
  hubNoProgramme: 'No programme information',
  hubLoadingEpg: 'Fetching guide…',
  hubNext: 'Next',
  nextAt: 'Next: {title} · {time}',
  hubPin: 'Add to favourites',
  hubUnpin: 'Remove from favourites',
  channelsCount: '{count} channels',
  minutesLeft: '{min} min left',
  // Hubb
  hubOpenGrid: 'All channels',
  hubOpenGuide: 'Channel guide',
  hubGuideKicker: 'Full channel guide',
  hubGuideTitle: 'See everything on tonight',
  hubGuideBody: 'Browse channels against time, set reminders and start with replays.',
  openEpg: 'Open EPG',
  hubFavorites: 'Your favourite channels',
  hubFavoritesEmpty: 'No favourites yet. Tap the heart on a channel to pin it here.',
  hubContinue: 'Continue watching',
  hubContinueCatchUp: 'Replays & catch-up',
  hubContinueRecent: 'Recently watched',
  hubContinueEmpty: 'Channels you watch show up here.',
  hubRemoveRecent: 'Remove from Continue watching',
  hubRecommended: 'Recommended for you',
  hubRecommendedBecause: 'You often watch {group}',
  hubRecommendedFavourite: 'Because you follow {channel}',
  hubAllChannels: 'All channels',
  channelsIn: '{count} channels in {group}',
  hubShowAllInGrid: 'Show all {count} channels',
  hubWatchedAt: 'Watched {time}',
  hubYesterday: 'yesterday',
  availableDays: 'Available for {days} days',
  availableHours: 'Available for {hours} h',
  hubEmptyTitle: 'No channels yet',
  hubEmptyBody: 'Add an M3U playlist or an Xtream login under Settings → Live TV.',
  // EPG
  epgTitle: 'EPG grid',
  guideToday: 'Today',
  guideTomorrow: 'Tomorrow',
  guideNow: 'Now',
  nowAt: 'Now {time}',
  guideWatch: 'Watch',
  reminder: 'Reminder',
  reminderOn: 'Reminder set',
  reminderOff: 'Remind me',
  epgEmpty: 'No programme guide for these channels yet. Add an EPG source under Settings → Live TV.',
  // Kanaldetalj
  channelTitle: 'Channel',
  today: 'Today',
  replays: 'Available as replay',
  channelInfo: 'Channel information',
  quality: 'Quality',
  language: 'Language',
  subtitles: 'Subtitles',
  group: 'Group',
  sourceList: 'Source',
  epgSource: 'Programme guide',
  yes: 'Yes',
  no: 'No',
  unknown: 'Unknown',
  parental: 'Parental control',
  parentalBody: 'Lock this channel behind the profile PIN.',
  lockedWithPin: 'Locked with PIN',
  noRestriction: 'No restriction',
  locked: 'Locked',
  enterPin: 'Enter the profile PIN',
  pinWrong: 'Wrong PIN. Try again.',
  pinMissing: 'Set a PIN on your profile first (Settings → Profiles).',
  unlock: 'Unlock',
  cancel: 'Cancel',
  // Spelare
  nextUp: 'Next up',
  inMinutes: 'in {min} min',
  guide: 'Guide',
  // Sök
  searchPlaceholder: 'Search channels and programmes',
  filterAll: 'All',
  filterChannels: 'Channels',
  filterProgrammes: 'Programmes',
  programmesToday: 'Programmes today',
  noResults: 'Nothing matched "{query}".',
  // Påminnelser
  remindersEmpty: 'No reminders. Tap the bell on a programme to add one.',
  remove: 'Remove',
  startsNow: 'Starts now on {channel}',
  startsIn: 'Starts in {min} min on {channel}',
  watch: 'Watch',
  dismiss: 'Dismiss',
  catchUp: 'Replay',
  // M3U-hämtning
  m3uFetchProgress: 'Fetching list {current} of {total}…',
  m3uFetchedAt: 'fetched {time}',
  m3uNeverFetched: 'not fetched yet',
  m3uFetchFailedOn: 'Could not fetch {host}: {error}',
  m3uFetchKeepOpen: 'This can take a while for a large playlist. You can leave this page — the fetch keeps running.',
  hubShowingOf: 'Showing {shown} of {total} in {group}',
  hubShowMore: 'Show more',
  epgShowingRows: 'Showing {shown} channels with a guide',
  epgAllWithGuide: 'All {shown} channels with a guide',
} as const

const SV: Record<keyof typeof EN, string> = {
  hubTitle: 'Live TV',
  back: 'Tillbaka',
  search: 'Sök',
  reminders: 'Påminnelser',
  hubAllGroups: 'Alla',
  hubLive: 'LIVE',
  hubWatchNow: 'Titta nu',
  pip: 'Bild-i-bild',
  hubNoProgramme: 'Ingen programinformation',
  hubLoadingEpg: 'Hämtar tablå…',
  hubNext: 'Sen',
  nextAt: 'Sen: {title} · {time}',
  hubPin: 'Lägg till i favoriter',
  hubUnpin: 'Ta bort från favoriter',
  channelsCount: '{count} kanaler',
  minutesLeft: '{min} min kvar',
  hubOpenGrid: 'Alla kanaler',
  hubOpenGuide: 'Kanalguide',
  hubGuideKicker: 'Full kanalguide',
  hubGuideTitle: 'Se allt som sänds ikväll',
  hubGuideBody: 'Bläddra kanal × tid, sätt påminnelser och kom igång med repriser.',
  openEpg: 'Öppna EPG',
  hubFavorites: 'Dina favoritkanaler',
  hubFavoritesEmpty: 'Inga favoriter ännu. Tryck på hjärtat på en kanal för att fästa den här.',
  hubContinue: 'Fortsätt titta',
  hubContinueCatchUp: 'Repriser & catch-up',
  hubContinueRecent: 'Senast sedda',
  hubContinueEmpty: 'Kanaler du tittar på dyker upp här.',
  hubRemoveRecent: 'Ta bort från Fortsätt titta',
  hubRecommended: 'Rekommenderat för dig',
  hubRecommendedBecause: 'Du ser ofta {group}',
  hubRecommendedFavourite: 'Eftersom du följer {channel}',
  hubAllChannels: 'Alla kanaler',
  channelsIn: '{count} kanaler i {group}',
  hubShowAllInGrid: 'Visa alla {count} kanaler',
  hubWatchedAt: 'Sågs {time}',
  hubYesterday: 'i går',
  availableDays: 'Tillgänglig i {days} dagar',
  availableHours: 'Tillgänglig i {hours} h',
  hubEmptyTitle: 'Inga kanaler ännu',
  hubEmptyBody: 'Lägg till en M3U-lista eller en Xtream-inloggning under Inställningar → Live TV.',
  epgTitle: 'EPG-rutnät',
  guideToday: 'Idag',
  guideTomorrow: 'Imorgon',
  guideNow: 'Nu',
  nowAt: 'Nu {time}',
  guideWatch: 'Titta',
  reminder: 'Påminnelse',
  reminderOn: 'Påminnelse satt',
  reminderOff: 'Påminn mig',
  epgEmpty: 'Ingen tablå för de här kanalerna ännu. Lägg till en EPG-källa under Inställningar → Live TV.',
  channelTitle: 'Kanaldetalj',
  today: 'Idag',
  replays: 'Tillgängligt för repris',
  channelInfo: 'Kanalinformation',
  quality: 'Kvalitet',
  language: 'Språk',
  subtitles: 'Undertext',
  group: 'Grupp',
  sourceList: 'Källa',
  epgSource: 'Tablå',
  yes: 'Ja',
  no: 'Nej',
  unknown: 'Okänt',
  parental: 'Föräldrakontroll',
  parentalBody: 'Lås kanalen bakom profilens PIN-kod.',
  lockedWithPin: 'Låst med PIN',
  noRestriction: 'Ingen begränsning',
  locked: 'Låst',
  enterPin: 'Ange profilens PIN-kod',
  pinWrong: 'Fel PIN-kod. Försök igen.',
  pinMissing: 'Sätt först en PIN-kod på profilen (Inställningar → Profiler).',
  unlock: 'Lås upp',
  cancel: 'Avbryt',
  nextUp: 'Näst upp',
  inMinutes: 'om {min} min',
  guide: 'Guide',
  searchPlaceholder: 'Sök kanaler och program',
  filterAll: 'Alla',
  filterChannels: 'Kanaler',
  filterProgrammes: 'Program',
  programmesToday: 'Program idag',
  noResults: 'Inget matchade "{query}".',
  remindersEmpty: 'Inga påminnelser. Tryck på klockan på ett program för att lägga till en.',
  remove: 'Ta bort',
  startsNow: 'Börjar nu på {channel}',
  startsIn: 'Börjar om {min} min på {channel}',
  watch: 'Titta',
  dismiss: 'Stäng',
  catchUp: 'Repris',
  // M3U-hämtning
  m3uFetchProgress: 'Hämtar lista {current} av {total}…',
  m3uFetchedAt: 'hämtad {time}',
  m3uNeverFetched: 'inte hämtad än',
  m3uFetchFailedOn: 'Kunde inte hämta {host}: {error}',
  m3uFetchKeepOpen: 'En stor spellista kan ta en stund. Du kan lämna sidan — hämtningen fortsätter.',
  hubShowingOf: 'Visar {shown} av {total} i {group}',
  hubShowMore: 'Visa fler',
  epgShowingRows: 'Visar {shown} kanaler med tablå',
  epgAllWithGuide: 'Alla {shown} kanaler med tablå',
}

export type HubStringKey = keyof typeof EN

export function hubText(lang: string | undefined, key: HubStringKey, vars?: Record<string, string | number>): string {
  const table = lang === 'sv' ? SV : EN
  let out: string = table[key] ?? EN[key]
  if (vars) {
    for (const [name, value] of Object.entries(vars)) out = out.split(`{${name}}`).join(String(value))
  }
  return out
}

export function useHubText() {
  const lang: string = useLang().lang
  const locale = lang === 'sv' ? 'sv-SE' : 'en-GB'
  return {
    lang,
    locale,
    h: (key: HubStringKey, vars?: Record<string, string | number>) => hubText(lang, key, vars),
  }
}
