'use client'

import { useCallback, useMemo } from 'react'
import { useLang } from '@/lib/plugin-sdk'

/**
 * TV-vyernas texter. Egen tabell (inte appens i18n): pluginet uppdateras
 * oberoende av appen, och nya nycklar i appen hade gett råa nyckelnamn på
 * äldre värdar. `{namn}` ersätts med vars.
 */
const EN = {
  // Ikonrad
  railSearch: 'Search',
  railHome: 'Home',
  railGuide: 'Channel guide',
  railMultiview: 'Multiview',
  railFavourites: 'Favourites',
  railSettings: 'Settings',
  // Gemensamt
  liveTv: 'Live TV',
  live: 'LIVE',
  replay: 'Replay',
  remind: 'Remind',
  watchNow: 'Watch now',
  back: 'Back',
  showMore: 'Show more',
  minutesLeft: '{min} min left',
  channelsCount: '{count} channels',
  allPlaylists: 'All playlists',
  addPlaylist: '+ Add playlist…',
  allGroups: 'All',
  favourites: 'Favourites',
  noProgramme: 'No programme information',
  loadingGuide: 'Fetching guide…',
  loadingChannels: 'Fetching channels…',
  okWatch: 'OK = watch',
  okRemind: 'OK = remind me',
  reminderSet: 'Reminder set',
  helpHub: 'OK = watch · hold OK = menu',
  helpGuide: 'OK watch · hold OK menu · ◂▸ category',
  helpPlaylists: '◂ ▸ switch column · Back closes',
  helpFavourites: 'OK = watch · hold OK = move up/down, remove, channel details · favourites come first in the guide and zap with 1–N on the remote',
  // Menyer
  menuAddFavourite: 'Add to favourites',
  menuRemoveFavourite: 'Remove from favourites',
  menuChannelDetails: 'Channel details',
  menuAddMultiview: 'Add to multiview',
  menuLock: 'Lock with PIN',
  menuUnlock: 'Unlock',
  menuMoveUp: 'Move up',
  menuMoveDown: 'Move down',
  menuGuide: 'Guide (now / next)',
  menuMultiview: 'Multiview',
  menuPause: 'Pause',
  menuResume: 'Resume',
  menuAudioHere: 'Audio here',
  menuSwitchChannel: 'Switch channel',
  menuEnlarge: 'Enlarge',
  menuFullscreen: 'Fullscreen',
  menuRemoveTile: 'Remove tile',
  addedToMultiview: 'Added to multiview',
  // Hubb
  spotlightFavouriteLive: 'Favourite · live',
  spotlightFavourite: 'Favourite',
  spotlightRecent: 'Last watched',
  spotlightOnNow: 'On now',
  continueWatching: 'Continue watching',
  continueSub: 'Replays & last watched',
  allChannels: 'All channels',
  allChannelsSub: '{playlist} · {count} channels · OK = watch · hold OK = menu',
  emptyTitle: 'No channels yet',
  emptyBody: 'Add an M3U playlist or an Xtream login under Settings.',
  openSettings: 'Open settings',
  searchPlaceholder: 'Search channels and programmes',
  // Guide
  colChannel: 'CHANNEL',
  colNow: 'NOW',
  colNext: 'NEXT',
  colLater: 'LATER',
  modeNow: 'Now / Next',
  modeTimeline: 'Timeline',
  modePlaylists: 'Playlists',
  next: 'Next',
  later: 'Later',
  previewLabel: 'live stream, muted · OK = fullscreen',
  previewFrame: 'saved frame · OK = fullscreen',
  // Favoriter
  favouritesSub: '{count} channels · order sets channel numbers 1–{count}',
  addFromGuide: '+ Add from the guide',
  favouritesEmpty: 'No favourites yet. Hold OK on a channel and choose Add to favourites.',
  // Kanaldetalj
  yesterday: 'Yesterday',
  today: 'Today',
  tomorrow: 'Tomorrow',
  playReplay: 'Play replay',
  remindMe: 'Remind me',
  removeReminder: 'Remove reminder',
  airedAt: 'Aired {time} · {channel}',
  startsAt: 'starts {time}',
  onNow: 'on now',
  replayAvailable: 'replay · available {days} days',
  channelInfo: 'CHANNEL INFORMATION',
  quality: 'Quality',
  source: 'Source',
  replayDays: 'Replay',
  daysCount: '{days} days',
  lockWithPin: 'Lock with profile PIN',
  noArchive: 'None',
  // Sök
  searchChannels: 'Channels',
  searchProgrammes: 'Programmes today',
  hits: '{count} hits',
  keyDone: 'Done',
  keySymbols: '123?',
  keyLetters: 'ABC',
  noResults: 'No results',
  // Multivy
  multiview: 'Multiview',
  layout2: '2 tiles',
  layout3: '1 + 2',
  layout4: '4 tiles',
  audioLabel: 'Audio',
  multiviewHelp: 'OK on a tile = audio here · hold OK = switch channel / remove',
  pickChannel: 'Pick channel',
  pickChannelFor: 'Pick channel for tile {n}',
  frameLabel: 'frame',
  tileFailed: 'Could not play',
  // Inställningar
  tabAppearance: 'Appearance',
  tabPlaylists: 'Playlists',
  tabEpg: 'EPG sources',
  tabParental: 'Parental control',
  accentColour: 'Accent colour',
  guideDefault: 'Channel guide default view',
  guideDefaultHint: 'Can also be switched inside the guide',
  behaviour: 'Behaviour',
  settingPreview: 'Preview in the channel guide (plays the stream muted)',
  settingStartLast: 'Start on the last channel',
  settingNumericZap: 'Number keys zap directly',
  settingBannerHide: 'Hide the info banner after',
  never: 'Never',
  seconds: '{s} s',
  addM3u: 'Add M3U URL',
  addXtream: 'Add Xtream login',
  refetch: 'Refetch',
  refetching: 'Fetching…',
  importProgress: 'Fetching {received} of {total}…',
  importProgressUnknown: 'Fetching…',
  importParsing: 'Reading the playlist…',
  importWriting: 'Saving the channels…',
  importFailed: 'The fetch failed',
  needsReimport: 'Needs refetching',
  truncated: 'The playlist was cut off at 64 MiB — some channels are missing',
  appTooOld: 'Live TV requires Lumio 0.1.596 or newer',
  xtreamServer: 'Xtream server — http://host:8080',
  xtreamUsername: 'Xtream username',
  xtreamPassword: 'Xtream password',
  xtreamNeedsLogin: 'Sign in again to fetch channels',
  xtreamLoginFailed: 'Could not sign in to the panel',
  remove: 'Remove',
  fetchedAt: 'fetched {time}',
  addEpgUrl: 'Add EPG URL',
  lockedChannels: 'Locked channels',
  noLocked: 'No locked channels',
  unlock: 'Unlock',
  enterPin: 'Enter PIN',
  pinWrong: 'Wrong PIN',
  cancel: 'Cancel',
  // Spelare
  playerHelp: '▾ guide · hold OK = menu',
  moreActions: 'More',
  nextLabel: 'Next',
  zapMiss: 'No channel {n}',
  // Tomma
  guideEmpty: 'No channels in this category',
} as const

const SV: Record<keyof typeof EN, string> = {
  railSearch: 'Sök',
  railHome: 'Hem',
  railGuide: 'Kanalguide',
  railMultiview: 'Multivy',
  railFavourites: 'Favoriter',
  railSettings: 'Inställningar',
  liveTv: 'Live TV',
  live: 'LIVE',
  replay: 'Repris',
  remind: 'Påminn',
  watchNow: 'Titta nu',
  back: 'Tillbaka',
  showMore: 'Visa fler',
  minutesLeft: '{min} min kvar',
  channelsCount: '{count} kanaler',
  allPlaylists: 'Alla spellistor',
  addPlaylist: '+ Lägg till spellista …',
  allGroups: 'Alla',
  favourites: 'Favoriter',
  noProgramme: 'Ingen programinformation',
  loadingGuide: 'Hämtar tablå…',
  loadingChannels: 'Hämtar kanaler…',
  okWatch: 'OK = titta',
  okRemind: 'OK = påminn mig',
  reminderSet: 'Påminnelse satt',
  helpHub: 'OK = titta · håll OK = meny',
  helpGuide: 'OK titta · håll OK meny · ◂▸ kategori',
  helpPlaylists: '◂ ▸ byter kolumn · Back stänger',
  helpFavourites: 'OK = titta · håll OK = flytta upp/ner, ta bort, kanaldetaljer · favoriter ligger först i guiden och zappas med 1–N på fjärren',
  menuAddFavourite: 'Lägg till i favoriter',
  menuRemoveFavourite: 'Ta bort från favoriter',
  menuChannelDetails: 'Kanaldetaljer',
  menuAddMultiview: 'Lägg till i multivy',
  menuLock: 'Lås med PIN',
  menuUnlock: 'Lås upp',
  menuMoveUp: 'Flytta upp',
  menuMoveDown: 'Flytta ner',
  menuGuide: 'Guide (nu / sen)',
  menuMultiview: 'Multivy',
  menuPause: 'Pausa',
  menuResume: 'Fortsätt',
  menuAudioHere: 'Ljud hit',
  menuSwitchChannel: 'Byt kanal',
  menuEnlarge: 'Förstora',
  menuFullscreen: 'Helskärm',
  menuRemoveTile: 'Ta bort ruta',
  addedToMultiview: 'Tillagd i multivyn',
  spotlightFavouriteLive: 'Favorit · live',
  spotlightFavourite: 'Favorit',
  spotlightRecent: 'Senast sedd',
  spotlightOnNow: 'Sänds nu',
  continueWatching: 'Fortsätt titta',
  continueSub: 'Repriser & senast sedda',
  allChannels: 'Alla kanaler',
  allChannelsSub: '{playlist} · {count} kanaler · OK = titta · håll OK = meny',
  emptyTitle: 'Inga kanaler än',
  emptyBody: 'Lägg till en M3U-spellista eller en Xtream-inloggning under Inställningar.',
  openSettings: 'Öppna inställningar',
  searchPlaceholder: 'Sök kanaler och program',
  colChannel: 'KANAL',
  colNow: 'NU',
  colNext: 'SEN',
  colLater: 'SENARE',
  modeNow: 'Nu / Sen',
  modeTimeline: 'Tablå',
  modePlaylists: 'Spellistor',
  next: 'Sen',
  later: 'Senare',
  previewLabel: 'liveström, tyst · OK = helskärm',
  previewFrame: 'sparad bildruta · OK = helskärm',
  favouritesSub: '{count} kanaler · ordningen styr kanalnummer 1–{count}',
  addFromGuide: '+ Lägg till från guiden',
  favouritesEmpty: 'Inga favoriter än. Håll OK på en kanal och välj Lägg till i favoriter.',
  yesterday: 'Igår',
  today: 'Idag',
  tomorrow: 'Imorgon',
  playReplay: 'Spela repris',
  remindMe: 'Påminn mig',
  removeReminder: 'Ta bort påminnelse',
  airedAt: 'Sändes {time} · {channel}',
  startsAt: 'börjar {time}',
  onNow: 'pågår nu',
  replayAvailable: 'repris · tillgänglig {days} dagar',
  channelInfo: 'KANALINFORMATION',
  quality: 'Kvalitet',
  source: 'Källa',
  replayDays: 'Repris',
  daysCount: '{days} dagar',
  lockWithPin: 'Lås med profilens PIN',
  noArchive: 'Ingen',
  searchChannels: 'Kanaler',
  searchProgrammes: 'Program idag',
  hits: '{count} träffar',
  keyDone: 'Klar',
  keySymbols: '123?',
  keyLetters: 'ABC',
  noResults: 'Inga träffar',
  multiview: 'Multivy',
  layout2: '2 rutor',
  layout3: '1 + 2',
  layout4: '4 rutor',
  audioLabel: 'Ljud',
  multiviewHelp: 'OK på ruta = ljud hit · håll OK = byt kanal / ta bort',
  pickChannel: 'Välj kanal',
  pickChannelFor: 'Välj kanal för ruta {n}',
  frameLabel: 'bildruta',
  tileFailed: 'Kunde inte spela',
  tabAppearance: 'Utseende',
  tabPlaylists: 'Spellistor',
  tabEpg: 'EPG-källor',
  tabParental: 'Föräldrakontroll',
  accentColour: 'Accentfärg',
  guideDefault: 'Kanalguidens standardvy',
  guideDefaultHint: 'Går även att växla direkt i guiden',
  behaviour: 'Beteende',
  settingPreview: 'Förhandsvisning i kanalguiden (spelar strömmen tyst)',
  settingStartLast: 'Starta på senaste kanalen',
  settingNumericZap: 'Nummertangenter zappar direkt',
  settingBannerHide: 'Dölj infobannern efter',
  never: 'Aldrig',
  seconds: '{s} s',
  addM3u: 'Lägg till M3U-URL',
  addXtream: 'Lägg till Xtream-inloggning',
  refetch: 'Hämta om',
  refetching: 'Hämtar…',
  importProgress: 'Hämtar {received} av {total}…',
  importProgressUnknown: 'Hämtar…',
  importParsing: 'Läser spellistan…',
  importWriting: 'Sparar kanalerna…',
  importFailed: 'Hämtningen misslyckades',
  needsReimport: 'Behöver hämtas om',
  truncated: 'Spellistan kapades vid 64 MiB – vissa kanaler saknas',
  appTooOld: 'Live TV kräver Lumio 0.1.596 eller nyare',
  xtreamServer: 'Xtream-server — http://host:8080',
  xtreamUsername: 'Xtream-användarnamn',
  xtreamPassword: 'Xtream-lösenord',
  xtreamNeedsLogin: 'Logga in på nytt för att hämta kanaler',
  xtreamLoginFailed: 'Kunde inte logga in på panelen',
  remove: 'Ta bort',
  fetchedAt: 'hämtad {time}',
  addEpgUrl: 'Lägg till EPG-URL',
  lockedChannels: 'Låsta kanaler',
  noLocked: 'Inga låsta kanaler',
  unlock: 'Lås upp',
  enterPin: 'Ange PIN',
  pinWrong: 'Fel PIN',
  cancel: 'Avbryt',
  playerHelp: '▾ guide · håll OK = meny',
  moreActions: 'Mer',
  nextLabel: 'Sen',
  zapMiss: 'Ingen kanal {n}',
  guideEmpty: 'Inga kanaler i kategorin',
}

export type TvStringKey = keyof typeof EN

export function tvText(lang: string | undefined, key: TvStringKey, vars?: Record<string, string | number>): string {
  const table = lang === 'sv' ? SV : EN
  let out: string = table[key] ?? EN[key]
  if (vars) {
    for (const [name, value] of Object.entries(vars)) out = out.split(`{${name}}`).join(String(value))
  }
  return out
}

/**
 * `tt` och objektet är memoiserade per språk.
 *
 * En ny `tt`-funktion per rendering gjorde varje `useCallback`/`useMemo` som
 * beror på den instabil — i skalet räckte det för att hela `nav` skulle byta
 * identitet vid varje minuttick, och lagren (kanalväljaren, spellistmenyn)
 * körde då om sina öppningseffekter och slet fokus ur användarens händer.
 */
export function useTvText() {
  const lang: string = useLang().lang
  const tt = useCallback((key: TvStringKey, vars?: Record<string, string | number>) => tvText(lang, key, vars), [lang])
  return useMemo(() => ({ lang, locale: lang === 'sv' ? 'sv-SE' : 'en-GB', tt }), [lang, tt])
}
