'use client'

import { useCallback, useMemo } from 'react'
import { useLang } from '@/lib/plugin-sdk'

/**
 * TV-vyernas texter. Egen tabell (inte appens i18n): pluginet uppdateras
 * oberoende av appen, och nya nycklar i appen hade gett råa nyckelnamn på
 * äldre värdar. `{namn}` ersätts med vars.
 */
const EN = {
  // Ikonrad
  railSearch: 'Search',
  railHome: 'Home',
  railGuide: 'Channel guide',
  railMultiview: 'Multiview',
  railFavourites: 'Favourites',
  railSettings: 'Settings',
  railBack: 'Back', // P3
  // P3: "…"-knappen på hovring — tydlig affordans, ikon OCH verktygstips.
  moreOptions: 'More options',
  // Gemensamt
  liveTv: 'Live TV',
  live: 'LIVE',
  replay: 'Replay',
  remind: 'Remind',
  watchNow: 'Watch now',
  back: 'Back',
  showMore: 'Show more',
  minutesLeft: '{min} min left',
  channelsCount: '{count} channels',
  allPlaylists: 'All playlists',
  // Telefonens spellistark: rubriken får inte heta samma som första posten ("All playlists").
  playlists: 'Playlists',
  addPlaylist: '+ Add playlist…',
  allGroups: 'All',
  favourites: 'Favourites',
  noProgramme: 'No programme information',
  loadingGuide: 'Fetching guide…',
  loadingChannels: 'Fetching channels…',
  okWatch: 'OK = watch',
  okRemind: 'OK = remind me',
  reminderSet: 'Reminder set',
  // Menyer
  menuAddFavourite: 'Add to favourites',
  menuRemoveFavourite: 'Remove from favourites',
  menuChannelDetails: 'Channel details',
  menuAddMultiview: 'Add to multiview',
  menuLock: 'Lock with PIN',
  menuUnlock: 'Unlock',
  menuMoveUp: 'Move up',
  menuMoveDown: 'Move down',
  menuGuide: 'Guide (now / next)',
  menuMultiview: 'Multiview',
  menuPause: 'Pause',
  menuResume: 'Resume',
  menuAudioHere: 'Audio here',
  menuSwitchChannel: 'Switch channel',
  menuEnlarge: 'Enlarge',
  menuFullscreen: 'Fullscreen',
  menuRemoveTile: 'Remove tile',
  addedToMultiview: 'Added to multiview',
  // Hubb
  spotlightFavouriteLive: 'Favourite · live',
  spotlightFavourite: 'Favourite',
  spotlightRecent: 'Last watched',
  spotlightOnNow: 'On now',
  continueWatching: 'Continue watching',
  continueSub: 'Replays & last watched',
  allChannels: 'All channels',
  allChannelsSub: '{playlist} · {count} channels · OK = watch · hold OK = menu',
  // Rubrik utanför TV-läget (Jerrys återkoppling 2026-09-14): bara antalet,
  // ingen spellista och ingen fjärrhjälp — se `tv-hub.tsx`.
  allChannelsCount: 'All {count} channels',
  emptyTitle: 'No channels yet',
  emptyBody: 'Add an M3U playlist or an Xtream login under Settings.',
  openSettings: 'Open settings',
  searchPlaceholder: 'Search channels and programmes',
  // Guide
  colChannel: 'CHANNEL',
  colNow: 'NOW',
  colNext: 'NEXT',
  colLater: 'LATER',
  modeNow: 'Now / Next',
  modeTimeline: 'Timeline',
  modePlaylists: 'Playlists',
  modeGrid: 'Grid',
  // Rutnätet (spec 4.3) — skrivbordets tablå, med skrivbordets egna texter.
  gridToday: 'Today',
  gridTomorrow: 'Tomorrow',
  gridNow: 'Now',
  gridNowAt: 'Now {time}',
  gridShowing: 'Showing {shown} channels with a guide',
  gridAllWithGuide: 'All {shown} channels with a guide',
  gridEmpty: 'No programme guide for these channels yet. Add an EPG source under Settings → Live TV.',
  next: 'Next',
  later: 'Later',
  previewLabel: 'live stream, muted · OK = fullscreen',
  previewFrame: 'saved frame · OK = fullscreen',
  // Favoriter
  favouritesSub: '{count} channels · order sets channel numbers 1–{count}',
  addFromGuide: '+ Add from the guide',
  favouritesEmpty: 'No favourites yet. Hold OK on a channel and choose Add to favourites.',
  // Telefonens tomma läge: ingen fjärrkontrollstext (skiljer sig medvetet
  // från skrivbordets favouritesEmpty ovan).
  favouritesEmptyPhone: 'No favourites yet. Add channels from the guide.',
  // Telefonens redigeringsläge (dra-omordning)
  edit: 'Edit',
  done: 'Done',
  // Kanaldetalj
  yesterday: 'Yesterday',
  today: 'Today',
  tomorrow: 'Tomorrow',
  playReplay: 'Play replay',
  remindMe: 'Remind me',
  removeReminder: 'Remove reminder',
  airedAt: 'Aired {time} · {channel}',
  startsAt: 'starts {time}',
  onNow: 'on now',
  replayAvailable: 'replay · available {days} days',
  channelInfo: 'CHANNEL INFORMATION',
  quality: 'Quality',
  source: 'Source',
  replayDays: 'Replay',
  daysCount: '{days} days',
  lockWithPin: 'Lock with profile PIN',
  noArchive: 'None',
  // Kanaldetalj på telefon (Task 8)
  programmeSheetInfo: 'Channel info',
  replayDaysShort: 'Replay available {days} days',
  // Sök
  searchChannels: 'Channels',
  searchProgrammes: 'Programmes today',
  hits: '{count} hits',
  keyDone: 'Done',
  keySymbols: '123?',
  keyLetters: 'ABC',
  noResults: 'No results',
  // Multivy
  multiview: 'Multiview',
  layout2: '2 tiles',
  layout3: '1 + 2',
  layout4: '4 tiles',
  audioLabel: 'Audio',
  pickChannel: 'Pick channel',
  pickChannelFor: 'Pick channel for tile {n}',
  frameLabel: 'frame',
  tileFailed: 'Could not play',
  // Inställningar
  tabAppearance: 'Appearance',
  tabPlaylists: 'Playlists',
  tabEpg: 'EPG sources',
  tabParental: 'Parental control',
  accentColour: 'Accent colour',
  guideDefault: 'Channel guide default view',
  guideDefaultHint: 'Can also be switched inside the guide',
  behaviour: 'Behaviour',
  settingPreview: 'Preview in the channel guide (plays the stream muted)',
  settingStartLast: 'Start on the last channel',
  settingNumericZap: 'Number keys zap directly',
  settingBannerHide: 'Hide the info banner after',
  never: 'Never',
  seconds: '{s} s',
  addM3u: 'Add M3U URL',
  addXtream: 'Add Xtream login',
  refetch: 'Refetch',
  refetching: 'Fetching…',
  importProgress: 'Fetching {received} of {total}…',
  importProgressUnknown: 'Fetching…',
  importParsing: 'Reading the playlist…',
  importWriting: 'Saving the channels…',
  importFailed: 'The fetch failed',
  needsReimport: 'Needs refetching',
  // Logotypreserv (P6): switchen är en riktig växel (Toggle), inte en
  // Action-etikett som bär läget i sin text — annars ser den ut som samma
  // sorts knapp som Komplettera. Kompletteringens kvitto delar
  // text/parametrar med skrivbordets `logoCompleteResult` (hub-strings.ts).
  logoFallback: 'Logos',
  logoComplete: 'Complete',
  logoCompleteRunning: 'Completing…',
  logoCompleteResult: '{matched} of {total} completed',
  truncated: 'The playlist was cut off at 64 MiB — some channels are missing',
  appTooOld: 'Live TV requires Lumio 0.1.596 or newer',
  xtreamServer: 'Xtream server — http://host:8080',
  xtreamUsername: 'Xtream username',
  xtreamPassword: 'Xtream password',
  xtreamNeedsLogin: 'Sign in again to fetch channels',
  xtreamLoginFailed: 'Could not sign in to the panel',
  remove: 'Remove',
  fetchedAt: 'fetched {time}',
  addEpgUrl: 'Add EPG URL',
  lockedChannels: 'Locked channels',
  noLocked: 'No locked channels',
  unlock: 'Unlock',
  enterPin: 'Enter PIN',
  pinWrong: 'Wrong PIN',
  cancel: 'Cancel',
  // Snabbknappar (spec 4.4)
  createList: 'Create list',
  listName: 'List name',
  listChannels: 'Channels',
  pickChannels: 'Pick channels for {list}',
  listFull: 'The list is full',
  refetchAll: 'Refetch all',
  epgStatusTitle: 'EPG status',
  epgSourceStats: '{channels} channels · {programmes} programmes',
  epgNeverFetched: 'Never fetched',
  epgRefresh: 'Refetch EPG',
  epgRefreshing: 'Fetching EPG…',
  xtreamAccount: 'Xtream account',
  xtreamExpires: 'expires {date}',
  xtreamNoExpiry: 'no expiry date',
  xtreamMaxConnections: '{count} connections',
  xtreamAccountUnavailable: 'Could not read the account',
  xtreamCategories: 'Categories',
  xtreamCategoriesTitle: 'Xtream categories',
  xtreamAllCategories: 'All categories',
  // Spelare
  moreActions: 'More',
  nextLabel: 'Next',
  zapMiss: 'No channel {n}',
  // P13: pekarkontroller i spelarkromet, bara utanför TV-läget
  playerMute: 'Mute',
  playerUnmute: 'Unmute',
  playerVolume: 'Volume',
  playerFullscreen: 'Fullscreen',
  playerExitFullscreen: 'Exit fullscreen',
  playerAspect: 'Aspect ratio',
  // Tomma
  guideEmpty: 'No channels in this category',
  // Telefonens flik-rad + bottenark (fas 3)
  tabHome: 'Home',
  tabGuide: 'Guide',
  tabFavourites: 'Favourites',
  tabSearch: 'Search',
  tabMore: 'More',
  sheetMultiview: 'Multiview',
  sheetSettings: 'Settings',
  // Delade rader (P3): sök-varianten prefixar nu-titeln, förloppet visar minuter kvar
  nowPrefix: 'Now',
  minutesShort: '{min} min',
  // Guiden på telefon (P5): segmentväxeln Now/Timeline/Lists + sidtitel
  guideTitle: 'Guide',
  phoneModeNow: 'Now',
  phoneModeTimeline: 'Timeline',
  phoneModeLists: 'Lists',
  // Guiden · Lists på telefon (P7): filterfältet och Visa alla-raden per lista
  filterCategories: 'Filter categories',
  showAllCategories: 'Show all {count} categories',
} as const

const SV: Record<keyof typeof EN, string> = {
  railSearch: 'Sök',
  railHome: 'Hem',
  railGuide: 'Kanalguide',
  railMultiview: 'Multivy',
  railFavourites: 'Favoriter',
  railSettings: 'Inställningar',
  railBack: 'Tillbaka', // P3
  moreOptions: 'Fler val', // P3
  liveTv: 'Live TV',
  live: 'LIVE',
  replay: 'Repris',
  remind: 'Påminn',
  watchNow: 'Titta nu',
  back: 'Tillbaka',
  showMore: 'Visa fler',
  minutesLeft: '{min} min kvar',
  channelsCount: '{count} kanaler',
  allPlaylists: 'Alla spellistor',
  playlists: 'Spellistor',
  addPlaylist: '+ Lägg till spellista …',
  allGroups: 'Alla',
  favourites: 'Favoriter',
  noProgramme: 'Ingen programinformation',
  loadingGuide: 'Hämtar tablå…',
  loadingChannels: 'Hämtar kanaler…',
  okWatch: 'OK = titta',
  okRemind: 'OK = påminn mig',
  reminderSet: 'Påminnelse satt',
  menuAddFavourite: 'Lägg till i favoriter',
  menuRemoveFavourite: 'Ta bort från favoriter',
  menuChannelDetails: 'Kanaldetaljer',
  menuAddMultiview: 'Lägg till i multivy',
  menuLock: 'Lås med PIN',
  menuUnlock: 'Lås upp',
  menuMoveUp: 'Flytta upp',
  menuMoveDown: 'Flytta ner',
  menuGuide: 'Guide (nu / sen)',
  menuMultiview: 'Multivy',
  menuPause: 'Pausa',
  menuResume: 'Fortsätt',
  menuAudioHere: 'Ljud hit',
  menuSwitchChannel: 'Byt kanal',
  menuEnlarge: 'Förstora',
  menuFullscreen: 'Helskärm',
  menuRemoveTile: 'Ta bort ruta',
  addedToMultiview: 'Tillagd i multivyn',
  spotlightFavouriteLive: 'Favorit · live',
  spotlightFavourite: 'Favorit',
  spotlightRecent: 'Senast sedd',
  spotlightOnNow: 'Sänds nu',
  continueWatching: 'Fortsätt titta',
  continueSub: 'Repriser & senast sedda',
  allChannels: 'Alla kanaler',
  allChannelsSub: '{playlist} · {count} kanaler · OK = titta · håll OK = meny',
  allChannelsCount: 'Alla {count} kanaler',
  emptyTitle: 'Inga kanaler än',
  emptyBody: 'Lägg till en M3U-spellista eller en Xtream-inloggning under Inställningar.',
  openSettings: 'Öppna inställningar',
  searchPlaceholder: 'Sök kanaler och program',
  colChannel: 'KANAL',
  colNow: 'NU',
  colNext: 'SEN',
  colLater: 'SENARE',
  modeNow: 'Nu / Sen',
  modeTimeline: 'Tablå',
  modePlaylists: 'Spellistor',
  modeGrid: 'Rutnät',
  gridToday: 'Idag',
  gridTomorrow: 'Imorgon',
  gridNow: 'Nu',
  gridNowAt: 'Nu {time}',
  gridShowing: 'Visar {shown} kanaler med tablå',
  gridAllWithGuide: 'Alla {shown} kanaler med tablå',
  gridEmpty: 'Ingen tablå för de här kanalerna ännu. Lägg till en EPG-källa under Inställningar → Live TV.',
  next: 'Sen',
  later: 'Senare',
  previewLabel: 'liveström, tyst · OK = helskärm',
  previewFrame: 'sparad bildruta · OK = helskärm',
  favouritesSub: '{count} kanaler · ordningen styr kanalnummer 1–{count}',
  addFromGuide: '+ Lägg till från guiden',
  favouritesEmpty: 'Inga favoriter än. Håll OK på en kanal och välj Lägg till i favoriter.',
  favouritesEmptyPhone: 'Inga favoriter än. Lägg till kanaler från guiden.',
  edit: 'Redigera',
  done: 'Klar',
  yesterday: 'Igår',
  today: 'Idag',
  tomorrow: 'Imorgon',
  playReplay: 'Spela repris',
  remindMe: 'Påminn mig',
  removeReminder: 'Ta bort påminnelse',
  airedAt: 'Sändes {time} · {channel}',
  startsAt: 'börjar {time}',
  onNow: 'pågår nu',
  replayAvailable: 'repris · tillgänglig {days} dagar',
  channelInfo: 'KANALINFORMATION',
  quality: 'Kvalitet',
  source: 'Källa',
  replayDays: 'Repris',
  daysCount: '{days} dagar',
  lockWithPin: 'Lås med profilens PIN',
  noArchive: 'Ingen',
  programmeSheetInfo: 'Kanalinfo',
  replayDaysShort: 'Repris {days} dagar',
  searchChannels: 'Kanaler',
  searchProgrammes: 'Program idag',
  hits: '{count} träffar',
  keyDone: 'Klar',
  keySymbols: '123?',
  keyLetters: 'ABC',
  noResults: 'Inga träffar',
  multiview: 'Multivy',
  layout2: '2 rutor',
  layout3: '1 + 2',
  layout4: '4 rutor',
  audioLabel: 'Ljud',
  pickChannel: 'Välj kanal',
  pickChannelFor: 'Välj kanal för ruta {n}',
  frameLabel: 'bildruta',
  tileFailed: 'Kunde inte spela',
  tabAppearance: 'Utseende',
  tabPlaylists: 'Spellistor',
  tabEpg: 'EPG-källor',
  tabParental: 'Föräldrakontroll',
  accentColour: 'Accentfärg',
  guideDefault: 'Kanalguidens standardvy',
  guideDefaultHint: 'Går även att växla direkt i guiden',
  behaviour: 'Beteende',
  settingPreview: 'Förhandsvisning i kanalguiden (spelar strömmen tyst)',
  settingStartLast: 'Starta på senaste kanalen',
  settingNumericZap: 'Nummertangenter zappar direkt',
  settingBannerHide: 'Dölj infobannern efter',
  never: 'Aldrig',
  seconds: '{s} s',
  addM3u: 'Lägg till M3U-URL',
  addXtream: 'Lägg till Xtream-inloggning',
  refetch: 'Hämta om',
  refetching: 'Hämtar…',
  importProgress: 'Hämtar {received} av {total}…',
  importProgressUnknown: 'Hämtar…',
  importParsing: 'Läser spellistan…',
  importWriting: 'Sparar kanalerna…',
  importFailed: 'Hämtningen misslyckades',
  needsReimport: 'Behöver hämtas om',
  logoFallback: 'Logotyper',
  logoComplete: 'Komplettera',
  logoCompleteRunning: 'Kompletterar…',
  logoCompleteResult: '{matched} av {total} kompletterade',
  truncated: 'Spellistan kapades vid 64 MiB – vissa kanaler saknas',
  appTooOld: 'Live TV kräver Lumio 0.1.596 eller nyare',
  xtreamServer: 'Xtream-server — http://host:8080',
  xtreamUsername: 'Xtream-användarnamn',
  xtreamPassword: 'Xtream-lösenord',
  xtreamNeedsLogin: 'Logga in på nytt för att hämta kanaler',
  xtreamLoginFailed: 'Kunde inte logga in på panelen',
  remove: 'Ta bort',
  fetchedAt: 'hämtad {time}',
  addEpgUrl: 'Lägg till EPG-URL',
  lockedChannels: 'Låsta kanaler',
  noLocked: 'Inga låsta kanaler',
  unlock: 'Lås upp',
  enterPin: 'Ange PIN',
  pinWrong: 'Fel PIN',
  cancel: 'Avbryt',
  createList: 'Skapa lista',
  listName: 'Listans namn',
  listChannels: 'Kanaler',
  pickChannels: 'Välj kanaler för {list}',
  listFull: 'Listan är full',
  refetchAll: 'Hämta om alla',
  epgStatusTitle: 'EPG-status',
  epgSourceStats: '{channels} kanaler · {programmes} program',
  epgNeverFetched: 'Aldrig hämtad',
  epgRefresh: 'Hämta om EPG',
  epgRefreshing: 'Hämtar EPG…',
  xtreamAccount: 'Xtream-konto',
  xtreamExpires: 'giltigt till {date}',
  xtreamNoExpiry: 'inget utgångsdatum',
  xtreamMaxConnections: '{count} anslutningar',
  xtreamAccountUnavailable: 'Kunde inte läsa kontot',
  xtreamCategories: 'Kategorier',
  xtreamCategoriesTitle: 'Xtream-kategorier',
  xtreamAllCategories: 'Alla kategorier',
  moreActions: 'Mer',
  nextLabel: 'Sen',
  zapMiss: 'Ingen kanal {n}',
  // P13
  playerMute: 'Ljud av',
  playerUnmute: 'Ljud på',
  playerVolume: 'Volym',
  playerFullscreen: 'Fullskärm',
  playerExitFullscreen: 'Lämna fullskärm',
  playerAspect: 'Bildförhållande',
  guideEmpty: 'Inga kanaler i kategorin',
  // Telefonens flik-rad + bottenark (fas 3)
  tabHome: 'Hem',
  tabGuide: 'Guide',
  tabFavourites: 'Favoriter',
  tabSearch: 'Sök',
  tabMore: 'Mer',
  sheetMultiview: 'Multivy',
  sheetSettings: 'Inställningar',
  nowPrefix: 'Nu',
  minutesShort: '{min} min',
  guideTitle: 'Guide',
  phoneModeNow: 'Nu',
  phoneModeTimeline: 'Tablå',
  phoneModeLists: 'Listor',
  filterCategories: 'Filtrera kategorier',
  showAllCategories: 'Visa alla {count} kategorier',
}

export type TvStringKey = keyof typeof EN

export function tvText(lang: string | undefined, key: TvStringKey, vars?: Record<string, string | number>): string {
  const table = lang === 'sv' ? SV : EN
  let out: string = table[key] ?? EN[key]
  if (vars) {
    for (const [name, value] of Object.entries(vars)) out = out.split(`{${name}}`).join(String(value))
  }
  return out
}

/**
 * `tt` och objektet är memoiserade per språk.
 *
 * En ny `tt`-funktion per rendering gjorde varje `useCallback`/`useMemo` som
 * beror på den instabil — i skalet räckte det för att hela `nav` skulle byta
 * identitet vid varje minuttick, och lagren (kanalväljaren, spellistmenyn)
 * körde då om sina öppningseffekter och slet fokus ur användarens händer.
 */
export function useTvText() {
  const lang: string = useLang().lang
  const tt = useCallback((key: TvStringKey, vars?: Record<string, string | number>) => tvText(lang, key, vars), [lang])
  return useMemo(() => ({ lang, locale: lang === 'sv' ? 'sv-SE' : 'en-GB', tt }), [lang, tt])
}
